
import React from 'react';

interface StaticPageProps {
    onBack: () => void;
}

const StaticPageLayout: React.FC<{ title: string; onBack: () => void; children: React.ReactNode }> = ({ title, onBack, children }) => {
    return (
        <div className="relative z-10 w-full max-w-4xl mx-auto p-4 md:p-8 animate-fade-in text-ivory flex flex-col items-center flex-grow justify-center">
            <div className="w-full bg-charcoal/50 backdrop-blur-sm rounded-lg border border-gold/20 p-8 shadow-2xl shadow-gold/5">
                <h1 className="font-serif text-4xl md:text-5xl text-gold mb-6 text-center">{title}</h1>
                <div className="font-sans text-ivory/80 space-y-4 max-h-[60vh] overflow-y-auto pr-4">
                    {children}
                </div>
                <div className="text-center mt-8">
                    <button onClick={onBack} className="px-8 py-3 text-lg font-semibold text-ivory border-2 border-ivory/50 rounded-md hover:bg-ivory hover:text-charcoal transition-all duration-300">
                        Back to the Game
                    </button>
                </div>
            </div>
        </div>
    );
};

export const AboutPage: React.FC<StaticPageProps> = ({ onBack }) => (
    <StaticPageLayout title="About Truth or AI" onBack={onBack}>
        <p>Welcome to Truth or AI, an experiment where human curiosity collides with artificial intelligence. This is not just a game; it's a conversation with a digital mind, designed to be both playful and profound.</p>
        <p>Powered by Google's Gemini models, our AI is crafted to be a witty, mysterious, and engaging partner in this timeless game. It learns from countless texts, stories, and dialogues to create unique challenges that probe, entertain, and surprise.</p>
        <p>We believe in the elegant dance between logic and chaos. Each truth you tell and each dare you complete adds a whisper to the digital ether. What will you reveal? What will you become? The choice, as always, is yours.</p>
        <p>Dare to play with intelligence.</p>
    </StaticPageLayout>
);

export const PrivacyPage: React.FC<StaticPageProps> = ({ onBack }) => (
    <StaticPageLayout title="Privacy Policy" onBack={onBack}>
        <h2 className="text-xl font-bold text-gold">Our Commitment to Your Privacy</h2>
        <p>Your privacy is paramount. This game is designed as an anonymous experience. We do not require you to create an account or provide any personally identifiable information (PII) to play.</p>
        <p>When you submit a response to "The Hall of Chaos," it is done so anonymously. We do not link submissions to any user session or IP address. The content is moderated to ensure a safe environment, but the submissions themselves are ephemeral and untraceable to you.</p>
        <p>We do not sell or share your data with third parties. Any interaction with the AI is processed by Google's Gemini API under their privacy policies. We do not store the prompts or your responses on our servers.</p>
        <p>This policy may be updated in the future, especially if we introduce features like user accounts. We will notify users of any significant changes.</p>
    </StaticPageLayout>
);

export const TermsPage: React.FC<StaticPageProps> = ({ onBack }) => (
     <StaticPageLayout title="Terms of Use" onBack={onBack}>
        <p>By accessing and playing "Truth or AI," you agree to these Terms of Use. If you do not agree, please do not use this service.</p>
        <h2 className="text-xl font-bold text-gold mt-4">1. Responsible Play</h2>
        <p>You agree to use this service responsibly. The "Dares" are designed to be safe and performable anywhere. Do not attempt any action that could cause harm to yourself, others, or property. You are solely responsible for your actions.</p>
        <h2 className="text-xl font-bold text-gold mt-4">2. Age Restriction</h2>
        <p>This game is intended for users aged 13 and older. By playing, you confirm that you meet this age requirement.</p>
        <h2 className="text-xl font-bold text-gold mt-4">3. Content</h2>
        <p>The content generated by the AI is for entertainment purposes only. While we strive for high-quality and appropriate prompts, we are not responsible for any generated content you may find offensive or inappropriate. Submissions to "The Hall of Chaos" must not contain hateful, illegal, or explicit content.</p>
        <h2 className="text-xl font-bold text-gold mt-4">4. Disclaimer of Warranty</h2>
        <p>This service is provided "as is," without any warranties of any kind. We do not guarantee that the service will be available, uninterrupted, or error-free.</p>
     </StaticPageLayout>
);

export const CookiesPage: React.FC<StaticPageProps> = ({ onBack }) => (
    <StaticPageLayout title="Cookies Policy" onBack={onBack}>
        <p>Like most websites, "Truth or AI" may use cookies to enhance your experience. This policy explains what cookies are and how we use them.</p>
        <h2 className="text-xl font-bold text-gold mt-4">What Are Cookies?</h2>
        <p>Cookies are small text files stored on your device (computer, tablet, mobile phone) when you visit a website. They help the website recognize your device and remember information about your visit, such as your preferences.</p>
        <h2 className="text-xl font-bold text-gold mt-4">How We Use Cookies</h2>
        <p>Currently, our use of cookies is minimal. We may use them for:</p>
        <ul className="list-disc list-inside space-y-2">
            <li><strong>Essential Functionality:</strong> To ensure the site runs smoothly. These are strictly necessary and do not require consent.</li>
            <li><strong>Performance and Analytics:</strong> In the future, we may use anonymous analytics cookies to understand how users interact with our site, helping us to improve it. These cookies do not identify you personally.</li>
        </ul>
        <h2 className="text-xl font-bold text-gold mt-4">Your Choices</h2>
        <p>You can manage or delete cookies through your browser settings. However, please be aware that disabling essential cookies may affect the functionality of this website.</p>
    </StaticPageLayout>
);

export const HallOfChaosPage: React.FC<StaticPageProps> = ({ onBack }) => (
    <StaticPageLayout title="The Hall of Chaos" onBack={onBack}>
        <p className="text-center text-2xl">Echoes of truths and dares will soon resonate here.</p>
        <p>The Hall of Chaos is a forthcoming public gallery where the most intriguing, witty, and bold anonymous responses from players around the world will be displayed.</p>
        <p>It is a testament to the beautiful chaos that ensues when humanity plays with intelligence. Check back soon to witness the collection.</p>
    </StaticPageLayout>
);
